name: Build, Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
        npm install
    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git remote update
        npm run gh-deploy
        git push -f origin master:master
